# Generated by Django 3.2.7 on 2022-05-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='uniqueid',
        ),
        migrations.AlterField(
            model_name='lga',
            name='lga_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='uniquewardid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Election.ward'),
        ),
        migrations.AlterField(
            model_name='ward',
            name='lga_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Election.lga'),
        ),
    ]
