# Generated by Django 3.2.7 on 2022-05-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0002_auto_20220503_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='lga_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Election.lga'),
        ),
    ]
