# Generated by Django 3.2.7 on 2022-05-03 14:21

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0005_alter_pollingunit_polling_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='uniquewardid', chained_model_field='uniqueid', on_delete=django.db.models.deletion.CASCADE, to='Election.pollingunit'),
        ),
    ]
