# Generated by Django 3.2.7 on 2022-05-03 22:58

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0006_alter_pollingunit_polling_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcedpuresults',
            name='polling_unit_uniqueid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Election.pollingunit'),
        ),
        migrations.AlterField(
            model_name='pollingunit',
            name='polling_unit_id',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='uniquewardid', chained_model_field='uniquewardid', on_delete=django.db.models.deletion.CASCADE, to='Election.pollingunit'),
        ),
    ]
